### PR TITLE
VP-MISC Extend fetch API capabilities with extra request headers

### PR DESCRIPTION
**Pull request by cedricpim**
As the library gets more used, more uses cases are needed to support.
At this moment, we need the ability to provide some extra request
headers to the default ones, so that the logic specific to the
application being developed can be kept in the application code.

### CODE REVIEW

**Review by NoryDev — APPROVED** [review]
I'm fine with the change, but that made me thing: these headers (the original ones, from `requestHeaders()` function) feel pretty custom for a (public) component library. Should this really be in here? cc @alexmreis

**Comment by cedricpim** [comment]
> I'm fine with the change, but that made me thing: these headers (the original ones, from `requestHeaders()` function) feel pretty custom for a (public) component library. Should this really be in here? cc @alexmreis

We could just remove the requestHeaders function and make it mandatory to provide it to the other "helper" functions.

**Comment by NoryDev** [comment]
> > I'm fine with the change, but that made me thing: these headers (the original ones, from `requestHeaders()` function) feel pretty custom for a (public) component library. Should this really be in here? cc @alexmreis
> 
> We could just remove the requestHeaders function and make it mandatory to provide it to the other "helper" functions.

yeah right. that's a breaking change though. not sure if we want to go there.

**Review by alexmreis — APPROVED** [review]
Breaking change in `fetchResource` / `postResource` but seems like the only usages were inside `ui/Fetch.js` anyway.

**Pull request merged**
